export const LOGIN_USER_BEGIN = 'LOGIN_USER_BEGIN';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';
export const FETCH_PROFILE_SUCCESS = 'FETCH_PROFILE_SUCCESS';

export const FETCH_DEVELOPERS_BEGIN = 'FETCH_DEVELOPER_BEGIN';
export const FETCH_DEVELOPERS_SUCCESS = 'FETCH_DEVELOPER_SUCCESS';
export const FETCH_DEVELOPERS_ERROR = 'FETCH_DEVELOPER_ERROR';

export const FETCH_POSTS_BEGIN = 'FETCH_POSTS_BEGIN';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_ERROR = 'FETCH_POSTS_ERROR';

export const LIKE_POST = 'LIKE_POST';
export const CLEAR_SUCCESS = 'CLEAR_SUCCESS';
export const CLEAR_ERROR = 'CLEAR_ERROR';
export const LOGOUT = 'LOGOUT';
